services:
  mysql:
    image: mysql:8.0
    container_name: be-local-mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: hack_and_marathon_202601_be_local
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
